version: "3.7"

services:
  app:
    image: "pet-data-service"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: my-postgres
      DATABASE_PASSWORD: my-postgres
  db:
    image: "postgres:14"
    container_name: db
    environment:
      - POSTGRES_USER=my-postgres
      - POSTGRES_PASSWORD=my-postgres
