version: "3.8"

services:
  app:
    image: "pet-data-service"
    build:
      context: .
    container_name: app
    environment:
      DATABASE_HOST: "r2dbc:postgresql://db:5432/pet-service"
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: example
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
  db:
    image: pet-postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
