spring:
  application:
    name: petsore-data-service
  r2dbc:
    url: ${DATABASE_HOST:r2dbc:postgresql://localhost:5432/test}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD=mysecretpassword}
